### ISSUE TITLE
Async tests should await on save.

### ISSUE THREAD

**Issue by briosheje** [tomanagle/Mongoose-TypeScript-example#1]
https://github.com/tomanagle/Mongoose-TypeScript-example/blob/584ec066c2f3f65bffad0bce44848f72f4ceca03/src/models/__TESTS__/user.test.ts#L30

That line should add `await` so that the teardown won't throw an exception.

**Comment by tomanagle** [comment]
Thanks @briosheje 

The changed have been merged.

Tom
