### ISSUE TITLE
Need a concrete class

### ISSUE THREAD

**Issue by yashgt** [tomanagle/Mongoose-TypeScript-example#248]
User controller is creating a dynamic object while calling User.create. This object needs to have the same properties as defined in IUser.
I am not able to do something like :
new UserObj(x,y,x) and pass it to User.create. 
Ideally I would like to define a concrete class like UserObj , fill it, and then invoke the model functions. that possible?

**Comment by tomanagle** [comment]
@yashgt sorry I'm not sure what exactly you're looking for. Could you provide a code sample of what you want to do?
